### PR TITLE
Adding Header, SubNav and Styling for API IAM

### PR DESCRIPTION
**Pull request by siddhart-singhal**
[TD-1497](https://appdirect.jira.com/browse/TD-1497)

> Have a Look:

Screenshot 2019-11-25 at 12 23 11 PM
Screenshot 2019-11-25 at 12 23 22 PM

> Logo and Styling can be changed when we get the new designs in.

### CODE REVIEW

**Comment by siddhart-singhal** [comment]
Don't know why that check is failing.

**Comment by aaronbasdeo** [comment]
@adrienzieba do you know why the check is failing?

**Comment by adrienzieba** [comment]
@aaronbasdeo it is ok, it is because the branch was creating in AppDirect repo. The important check here is the one for the PR

**Comment by aaronbasdeo** [comment]
@siddhart-singhal this looks good. I'm wondering if we should use a different branch for this - I don't want to mess with anything on the site currently. What do you think?

**Comment by siddhart-singhal** [comment]
@aaronbasdeo Should I change the PR base from `master` to `dev` ?

**Comment by aaronbasdeo** [comment]
@siddhart-singhal yes

**Comment by siddhart-singhal** [comment]
Closing this PR as a new branch will be created against dev.

**Pull request closed without merging**
