### PR TITLE
Adding AppInsights Drop Down Link

### PR DESCRIPTION
**Pull request by SinghalSiddhart15**

### CODE REVIEW

**Comment by aaronbasdeo** [comment]
@SinghalSiddhart15 I am not able to merge this. Do you know who can?

**Comment by aaronbasdeo** [comment]
@adrienzieba @alexstojda do you guys have write access? Can you review? In any case, the check failed...

**Comment by adrienzieba** [comment]
Error during Docker image creation

```
ERROR:  While executing gem ... (OptionParser::InvalidOption)

    invalid option: --no-ri

The command '/bin/sh -c gem install --no-ri --no-rdoc bundler' returned a non-zero code: 1

```
https://github.com/bundler/heroku-buildpack-bundler2/pull/1#issuecomment-451654992

replace `--no-ri --no-rdoc ` by `--no-document`

**Comment by adrienzieba** [comment]
@aaronbasdeo I gave you write access.
you need to wait for the fix in the code

**Comment by SinghalSiddhart15** [comment]
@aaronbasdeo @adrienzieba Added the changes. All Checks are passed

**Pull request merged**
