### PR TITLE
Cosmetic Changes to Slate UI

### PR DESCRIPTION
**Pull request by SinghalSiddhart15**
Jira Link: https://appdirect.jira.com/browse/API-99

@alexbt @jerry-sherman @adimantrix Do have a look and let me know if any changes are required. Thanks!

ScreenShots: 

screen shot 2017-07-29 at 12 00 11 am
screen shot 2017-07-29 at 12 00 14 am

### CODE REVIEW

**Comment by alexbt** [comment]
LGTM - but I'd wait for @jerry-sherman and Aaron 's feedback

**Comment by SinghalSiddhart15** [comment]
Sure @alexbt .

**Comment by adimantrix** [comment]
IMO, we should merge this PR and incorporate any further UI review comments by Jerry, Aaron and Nick via another PR.

What say @alexbt @SinghalSiddhart15?

**Comment by SinghalSiddhart15** [comment]
Works for me @adimantrix

**Pull request merged**
